version: '3'

services:
  app:
    container_name: notification-service
    build: .
    restart: always
    env_file: .env
    expose:
      - ${NOTIFICATION_SERVICE_PORT}
    ports:
      - ${NOTIFICATION_SERVICE_PORT}:${NOTIFICATION_SERVICE_PORT}
    environment:
      - MAIL_HOST=${MAIL_HOST}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - API_GATEWAY_URL=${API_GATEWAY_URL}
      - NOTIFICATION_SERVICE_PORT=${NOTIFICATION_SERVICE_PORT}
      - RABBITMQ_URL=${RABBITMQ_URL}
    networks:
      - backend
    command: npm run start
    volumes:
      - .:/app
      - /app/node_modules
volumes:
  app:
networks:
  backend:
    driver: bridge    
