version: '3'

services:
  app:
    container_name: user-service
    depends_on:
      - dev-database
    build: .
    restart: always
    env_file: .env
    expose:
      - ${USER_SERVICE_PORT}
    ports:
      - ${USER_SERVICE_PORT}:${USER_SERVICE_PORT}
    environment:
      - USER_SERVICE_DATABASE=${USER_SERVICE_DATABASE}
      - NODE_ENV=${NODE_ENV}
      - USER_SERVICE_PORT=${USER_SERVICE_PORT}
      - RABBITMQ_URL=${RABBITMQ_URL}
    networks:
      - backend
    command: npm run start
    volumes:
      - .:/app
      - /app/node_modules
  dev-database:
    container_name: dev-database
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "password"
      MONGO_INITDB_DATABASE: "gateway-test"
    ports:
      - 27018:27017
    expose:
      - 27018
    volumes:
      - dev-database:/data/db
    restart: unless-stopped
    networks:
      - backend
  dev-rabbitmq:
    container_name: dev-rabbitmq
    image: rabbitmq:latest
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - 5672
    environment:
      RABBITMQ_DEFAULT_USER: "root"
      RABBITMQ_DEFAULT_PASS: "password"
    volumes:
      - dev-rabbitmq:/data/rabbitmq
    restart: unless-stopped

volumes:
  app:
  dev-database:
  dev-rabbitmq:
networks:
  backend:
    driver: bridge    
