version: '3'

services:
  app:
    container_name: user-service
    build: .
    restart: always
    env_file: .env
    expose:
      - ${USER_SERVICE_PORT}
    ports:
      - ${USER_SERVICE_PORT}:${USER_SERVICE_PORT}
    environment:
      - USER_SERVICE_DATABASE=${USER_SERVICE_DATABASE}
      - NODE_ENV=${NODE_ENV}
      - USER_SERVICE_PORT=${USER_SERVICE_PORT}
      - RABBITMQ_URL=${RABBITMQ_URL}
    networks:
      - backend
    command: npm run start
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  app:
networks:
  backend:
    driver: bridge    
